# Aerospike
# Requires Aerospike Server running locally
spring.aerospike.hosts=localhost:3000
spring.data.aerospike.namespace=test

# Set specific packages to DEBUG if required
#logging.level.com.demo.reactive=DEBUG
#logging.level.org.springframework.data=DEBUG