[[guide-getting-started-simple-crud]]
= Spring Data Aerospike: Getting Started

== How to set up Spring Data Aerospike in a Spring Boot application for basic CRUD operations
:toc:

:spring-boot-version: 3.4.1
:spring-data-aerospike-version: 5.0.0

== Setting up the project

In this section we'll cover setup of the project from the start.

First, we'll need to set up the basic project structure.
You can do it either manually if you are familiar with the process or do it via https://start.spring.io/[Spring Initializr].

In Spring Initializr you'll need to select:

- Project: https://stackoverflow.com/a/13335439/688926[Maven] project
- Language: Java
- https://spring.io/projects/spring-boot[Spring Boot]: {spring-boot-version}
- Java: 17

Press Generate button in the bottom of the page, and you'll get zip with initial project. Import project into your
favorite IDE and run the test. It should be green and that means that you are ready to continue to the next section.

== Adding `spring-data-aerospike` dependency

[NOTE]
====
https://github.com/aerospike/spring-data-aerospike[Spring Data Aerospike] is an Aerospike project,
and the dependency is not managed by Spring. It has its own release cycle not included into
Spring Boot dependency management. Available versions can be checked on
https://mvnrepository.com/artifact/com.aerospike/spring-data-aerospike[Maven Central].

https://github.com/aerospike/spring-data-aerospike?tab=readme-ov-file#spring-data-aerospike-compatibility[Compatibility table]
can be checked for the version of `spring-data-aerospike` that is compatible with the specific Spring Boot and
Aerospike Server versions.
====

In our case we are going to use `spring-data-aerospike` {spring-data-aerospike-version} as we have Spring Boot
{spring-boot-version}.

.pom.xml
[source,xml]
----
        <dependency>
            <groupId>com.aerospike</groupId>
            <artifactId>spring-data-aerospike</artifactId>
        </dependency>
----


== Creating Aerospike repository

We will be using https://projectlombok.org/[Lombok] library to omit the boilerplate code in the entity class.
Add `lombok` into your `pom.xml`:

.pom.xml
[source,xml]
----
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
----

We are going to use the movies domain in this project, so to be able to read and save our movies into Aerospike
we will need to create:

. document (entity) class that represents our domain model,
. repository class that provides https://en.wikipedia.org/wiki/CRUD[CRUD] operations.

Movie document class will look the following way:

.MovieDocument.java
[source,java]
----
@Value // <1>
@Document(collection = "demo-simplecrud-set") // <2>
@Builder(toBuilder = true) // <3>
// Spring Data object creation can use all-args constructor instead of reflection which is much faster
@AllArgsConstructor // <4>
public class MovieDocument {

    @Id // <5>
    String id;

    @Field // <6>
    String name;

    @Field("desc")  // <7>
    String description;

    @Indexed(type = IndexType.NUMERIC, collectionType = IndexCollectionType.DEFAULT) // <8>
    @Field
    int likes;

    @Field
    double rating;
}
----

Document explained:

<1> https://projectlombok.org/features/Value[`@Value`] makes class immutable, all fields are made private and final,
`toString()`, `equals()`, `hashCode()`, field getters and all args constructor are generated.

<2> `@Document(collection = "demo-simplecrud-set")` marks a class as an entity to be persisted to Aerospike.
It also allows to specify set name, expiration and touch on read values. In current example custom set name is specified
via `collection`. Please note that a set name cannot contain the ':' or ';' characters
(see more https://www.aerospike.com/docs/guide/limitations.html[limitations]).

<3> `@Builder` provide Builder API for a class.

<4> `@AllArgsConstructor` creates public all-args constructor for a class (which is hidden by `@Builder`).
Spring Data can use all-args constructor instead of reflection to https://docs.spring.io/spring-data/data-commons/docs/current/reference/html/#mapping.object-creation[gain performance boost] for object creation.

<5> `@Id` marks a field as the primary key.

<6> `@Field` is optional, can be set just for the clarity purpose.

<7> `@Field("desc")` configures the name of a field to be used when persisting the document. This value will be used as a bin name instead of the original field name.

<8> `@Indexed` creates https://www.aerospike.com/docs/architecture/secondary-index.html[secondary index] on application startup for the specific field. Note: `@Indexed` annotation is not supported for the fields annotated with `@Id`, `@Expiration` or `@Version` annotations.

[NOTE]
====
Aerospike has certain https://aerospike.com/docs/reference/limitations[limitations] including bin name length.
If your document contains field with name that exceeds this limit, specify short name in `@Field` annotation:
----
    @Field("shortName")
    String veeeeeryLoooongFieldName;
----
====

Create Movie Repository interface:

.MovieRepository.java
[source,java]
----
public interface MovieRepository extends AerospikeRepository<MovieDocument, String> { // <1>
}
----

Repository explained:

<1> `AerospikeRepository` provides
https://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html[Repository]
functionality for the entity class (standard CRUD + Aerospike specific operations).

== Configuring connection to Aerospike

To configure connection to Aerospike you'll need to create configuration class that extends
`AbstractAerospikeDataConfiguration`.

Basic setup requires one of these approaches:

* Configure `application.properties` using `spring.aerospike*` and `spring.data.aerospike*` prefixes.

* Override `getHosts()` and `nameSpace()` methods. You might also have to override `getClientPolicy()` method
to specify custom configuration for the Aerospike client, and `customConverters()` to add
https://aerospike.github.io/spring-data-aerospike/#aerospike.custom-converters[custom converters].

For more details, see https://aerospike.github.io/spring-data-aerospike/#configuration[Configuration] documentation.

Simple configuration will look the following way:

.AerospikeConfiguration.java
[source,java]
----
@Configuration
@EnableAerospikeRepositories(basePackageClasses = MovieRepository.class)
public class AerospikeConfiguration extends AbstractAerospikeDataConfiguration {

}
----

[[guide-getting-started-simple-crud-testing]]
== Testing

To verify that the repository is actually working let's add some basic tests:

.MovieRepositoryTests.java
[source,java]
----
public class MovieRepositoryTests extends SimpleCrudAerospikeDemoApplicationTest {

    String id;
    MovieDocument movie;

    @Autowired
    MovieRepository repository;

    @BeforeEach
    void setUp() {
        id = UUID.randomUUID().toString();
        movie = MovieDocument.builder()
                .id(id)
                .name("Back To the Future")
                .description("I finally invented something that works!")
                .rating(9.3)
                .likes(555_555)
                .build();
    }

    @Test
    public void saveMovie() {
        repository.save(movie);
        assertThat(repository.findById(id)).hasValue(movie);
    }

    @Test
    public void exists_returnsTrueIfMovieIsPresent() {
        repository.save(movie);
        assertThat(repository.existsById(id)).isTrue();
    }

    @Test
    public void deleteExistingMovieById() {
        repository.save(movie);
        repository.deleteById(id);
        assertThat(repository.findById(id)).isNotPresent();
    }

    @Test
    void deleteById_skipsNonExistingMovie() {
        repository.deleteById(id);
        repository.deleteById(id);
        assertThat(repository.findById(id)).isNotPresent();

        repository.save(movie);
        repository.deleteById("testId");
        assertThat(repository.findById(id)).isPresent();
        assertThat(repository.findById(id).get()).isEqualTo(movie);
    }
}
----

For the test purposes you can use
https://mvnrepository.com/artifact/com.playtika.testcontainers/embedded-aerospike[`embedded-aerospike`]
library based on https://mvnrepository.com/artifact/org.testcontainers/testcontainers[`testcontainers`].

NOTE: The `spring-cloud-starter-bootstrap` dependency is required to be present on classpath.
If you are not using Spring Cloud you can add `spring-cloud-starter-bootstrap` with `test` scope.

.pom.xml
[source,xml]
----
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.playtika.testcontainers</groupId>
            <artifactId>embedded-aerospike</artifactId>
            <scope>test</scope>
        </dependency>
----

This will set up Aerospike container when the test starts.

Add Aerospike configuration to the test resources:

./test/resources/application.properties
----
# Using embedded-aerospike
# The version can be controlled via bootstrap.properties
spring.aerospike.hosts=${embedded.aerospike.host}:${embedded.aerospike.port}
spring.data.aerospike.namespace=${embedded.aerospike.namespace}
----

and run the tests.


[[appendix]]
== Appendix

:leveloffset: +1

link:https://github.com/aerospike/spring-data-aerospike[Spring Data Aerospike]

link:https://docs.spring.io/spring-data/commons/reference/index.html[Spring Data Commons Documentation Reference]

link:https://docs.spring.io/spring-framework/reference/[Spring Framework Documentation Overview]

:leveloffset: -1

=== Demo application

:demo_path: ../examples/src/main/java/com/demo

To see demo application go to link:{demo_path}/simplecrud[Simple CRUD Demo].
