= Basic error handling

[quote, Werner Vogels]
Everything fails all the time.

Add `spring-retry` dependency together with `spring-boot-starter-aop`:

.pom.xml
[source,xml]
----
include::../pom.xml[tags=retry-deps]
----

You can either specify retry configuration directly via `@Retryable` properties or create `RetryInterceptor` bean and set it's name in `@Retryable` `interceptor` property.
For this demo we'll use simple configuration via `@Retryable`.

.MovieOperations.java
[source,java]
----
include::../src/main/java/com/example/demo/service/MovieOperations.java[]
----

<1> `@Retryable` specifies that the method(s) will be retied.
<2> `include` specifies exception types that should be retried.
<3> `maxAttempts` specifies number of max attempts of retries.
<4> `backoff` specifies backoff configuration for the retries.
<5> `random = true` enables jitter in backoff timeouts.

Add `@EnableRetry` either into existing `AerospikeConfiguration` or create separate class `AerospikeRetryConfiguration`:

.AerospikeRetryConfiguration.java
[source,java]
----
include::../src/main/java/com/example/demo/persistence/AerospikeRetryConfiguration.java[]
----

// TODO: add separate page about advanced topics
//- retryable, non retryable errors
//- why use exponential backoff with jitter
//- how to simulate network latencies