= Creating secondary index

TIP: For more details on secondary indexes please visit https://www.aerospike.com/docs/architecture/secondary-index.html[Aerospike Secondary Index official documentation].

Out of the box `spring-data-aerospike` supports creating secondary indexes in Aerospike.

There are two ways to accomplish this task:

. Using `AerospikeTemplate` `createIndex` method;
. Using `@Indexed` annotation placed over the field in your entity.

Let's dive into more details.


== Creating index via `AerospikeTemplate`

In this example we will create an index at startup of the application manually.

.AerospikeIndexConfiguration.java
[source,java]
----
include::../src/main/java/com/example/demo/persistence/index/AerospikeIndexConfiguration.java[]
----

== Creating index via `@Indexed` annotation

Place `@Indexed` annotation over the field in your entity and specify required types of the index.
This will make `spring-data-aerospike` to auto-create specfied secondary index in Aerospike on startup of your application.

[NOTE]
====
`@Indexed` annotation is not supported for the fields annotated with `@Id`, `@Expiration` or `@Version` annotations.
====

.IndexedDocument.java
[source,java]
----
include::../src/main/java/com/example/demo/persistence/index/IndexedDocument.java[]
----

== Testing

Verify indexes were created using the following tests:

.IndexTests.java
[source,java]
----
include::../src/test/java/com/example/demo/IndexTests.java[]
----

TIP: If you are not familiar on how to setup embedded Aerospike server for your tests please consult <<getting-started.adoc#, Getting started>> Testing section.

