# Github does not support include directives in asciidoc files, so we need to process them manually :(
# This workaround can be removed as soon as https://github.com/github/markup/issues/1095 is fixed
name: Process and commit documentation
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Process and commit documentation
    runs-on: ubuntu-latest
    steps:
      # Checkout repo using https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install Asciidoctor
        run: gem install asciidoctor

      - name: Process documentation
        run: |
          pushd scripts
          sh ./process_docs.sh
          popd

      - name: Commit and push processed documentation
        if: success()
        run: |
          pushd scripts
          sh ./commit_and_push.sh
          popd

